<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class TutorSeeder extends Seeder
{
    public function run(): void
    {
        $tutors = [
            [
                'first_names' => 'John',
                'last_names' => 'Smith',
                'email' => 'john.smith@example.com',
                'phone' => '3001234567',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Sarah',
                'last_names' => 'Johnson',
                'email' => 'sarah.johnson@example.com',
                'phone' => '3012345678',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Michael',
                'last_names' => 'Brown',
                'email' => 'michael.brown@example.com',
                'phone' => '3023456789',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Emily',
                'last_names' => 'Davis',
                'email' => 'emily.davis@example.com',
                'phone' => '3034567890',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Daniel',
                'last_names' => 'Wilson',
                'email' => 'daniel.wilson@example.com',
                'phone' => '3045678901',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Jessica',
                'last_names' => 'Taylor',
                'email' => 'jessica.taylor@example.com',
                'phone' => '3056789012',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'David',
                'last_names' => 'Anderson',
                'email' => 'david.anderson@example.com',
                'phone' => '3067890123',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Laura',
                'last_names' => 'Thomas',
                'email' => 'laura.thomas@example.com',
                'phone' => '3078901234',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'James',
                'last_names' => 'Jackson',
                'email' => 'james.jackson@example.com',
                'phone' => '3089012345',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Sophia',
                'last_names' => 'White',
                'email' => 'sophia.white@example.com',
                'phone' => '3090123456',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Robert',
                'last_names' => 'Harris',
                'email' => 'robert.harris@example.com',
                'phone' => '3101234567',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Olivia',
                'last_names' => 'Martin',
                'email' => 'olivia.martin@example.com',
                'phone' => '3112345678',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'William',
                'last_names' => 'Thompson',
                'email' => 'william.thompson@example.com',
                'phone' => '3123456789',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Emma',
                'last_names' => 'Garcia',
                'email' => 'emma.garcia@example.com',
                'phone' => '3134567890',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Joseph',
                'last_names' => 'Martinez',
                'email' => 'joseph.martinez@example.com',
                'phone' => '3145678901',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Ava',
                'last_names' => 'Robinson',
                'email' => 'ava.robinson@example.com',
                'phone' => '3156789012',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Charles',
                'last_names' => 'Clark',
                'email' => 'charles.clark@example.com',
                'phone' => '3167890123',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Mia',
                'last_names' => 'Rodriguez',
                'email' => 'mia.rodriguez@example.com',
                'phone' => '3178901234',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Thomas',
                'last_names' => 'Lewis',
                'email' => 'thomas.lewis@example.com',
                'phone' => '3189012345',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Isabella',
                'last_names' => 'Lee',
                'email' => 'isabella.lee@example.com',
                'phone' => '3190123456',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Christopher',
                'last_names' => 'Walker',
                'email' => 'christopher.walker@example.com',
                'phone' => '3201234567',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Charlotte',
                'last_names' => 'Hall',
                'email' => 'charlotte.hall@example.com',
                'phone' => '3212345678',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Anthony',
                'last_names' => 'Allen',
                'email' => 'anthony.allen@example.com',
                'phone' => '3223456789',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Amelia',
                'last_names' => 'Young',
                'email' => 'amelia.young@example.com',
                'phone' => '3234567890',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Matthew',
                'last_names' => 'Hernandez',
                'email' => 'matthew.hernandez@example.com',
                'phone' => '3245678901',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Harper',
                'last_names' => 'King',
                'email' => 'harper.king@example.com',
                'phone' => '3256789012',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
            [
                'first_names' => 'Andrew',
                'last_names' => 'Wright',
                'email' => 'andrew.wright@example.com',
                'phone' => '3267890123',
                'photo' => null,
                'password' => Hash::make('password123'),
                'role_id' => 2,
            ],
        ];

        foreach ($tutors as $tutor) {
            User::updateOrCreate(
                ['email' => $tutor['email']],
                $tutor
            );
        }
    }
}