<?php

namespace App;

use OpenApi\Attributes as OA;

#[OA\Info(
  version: '1.0.0',
  title: 'Tutor Reservation API',
  description: 'RESTful API for tutor reservations'
)]
#[OA\Server(
  url: 'http://127.0.0.1:8000',
  description: 'Main server'
)]
#[OA\SecurityScheme(
  securityScheme: 'sanctum',
  type: 'http',
  scheme: 'bearer',
  bearerFormat: 'JWT',
  description: 'Bearer token generated by Sanctum'
)]
class OpenApiSpec
{
  #[OA\Get(
    path: '/api/health',
    summary: 'Health check',
    tags: ['System'],
    responses: [
      new OA\Response(
        response: 200,
        description: 'OK'
      )
    ]
  )]
  public function health(): void {}
}
